services:
  _instanceof:
    Optimax\HealthCheckBundle\Service\HealthInterface:
      tags: ['health.service']

  Optimax\HealthCheckBundle\Controller\HealthController:
    autowire: true
    public: false
    autoconfigure: true
